### ISSUE TITLE
Amplicon coverage heatmap plot 

### ISSUE THREAD

**Issue by AnyaKovalenko** [jts/ncov-tools#106]
Dear @jts, 

please could you explain how to understand the density (the numbers: -2; -1; 0; 1; 2) on the heatmap amplicon coverage plot? Please see the attached pic. It does not look like the average depth and I am a little bit confused. 
Thank you again for this amazing tool, love it! 
best wishes

![heatmap_plot](https://user-images.githubusercontent.com/88783750/217615869-5685c5a4-62fd-4ffc-ba4a-bce8124b0d85.png)

**Comment by rdeborja** [comment]
Hi Anya,  the coverage is log transformed

https://github.com/jts/ncov-tools/blob/2332b92e319ea9fd691dbc914bdc106eaafaa4a0/workflow/scripts/plot/plot_amplicon_coverage_heatmap.R#L124

**Comment by AnyaKovalenko** [comment]
Hi @rdeborja, thank you mucho!
