### ISSUE TITLE
Rule 'make_sample_qc_summary': Hard-coded filenames

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-tools#12]
I've been having a bit of trouble running the `all_qc_summary` target.

It seems that the `make_sample_qc_summary` rule makes a few assumptions about filenames that aren't connected to the `config.yaml`

https://github.com/jts/ncov-tools/blob/8271770d662dbcf07d0f4f12611ad82781d0f398/qc/Snakefile#L333-L338

It seems to assume that input files are in a directory named `data` but most other rules seem to use the `data_root` value from the config file.

It also assumes that the consensus fasta is named like `{sample}.primertrimmed.consensus.fa` but other rules use the `consensus_pattern` value from the config file.

**Comment by jts** [comment]
Thanks for the report Dan, we’ll have a look.

Jared

**Comment by rdeborja** [comment]
Hi Dan.  I've just submitted a PR to address the hardcoded filenames and to stay consistent with the other file lookup functions in the Snakefile.  As for the trouble's you've been running into, the current implementation for the all_qc_summary works with Illumina data only.  I have some modifications to support nanopore runs and am currently implementing and testing them with the Snakefile for pipeline integration.  Which platform are you currently running?

**Comment by dfornika** [comment]
Thanks @rdeborja we're running both MinION and illumina.

**Comment by rdeborja** [comment]
@dfornika were you getting a specific error when running the qc pipeline?  Also, did it happen for both Illumina and nanopore runs?  I would like to try and replicate the problem before submitting any more changes.

**Comment by jts** [comment]
I believe this is now fixed with the updated QC modules.
