### ISSUE TITLE
augur mask support

### ISSUE THREAD

**Issue by fmaguire** [jts/ncov-tools#2]
Hi, 
Thanks for this pipeline, its really handy.  We are adding support to run it directly from the outputs of https://github.com/jaleezyy/covid-19-signal and were wondering if optionally supporting vcf based masking for the augur analysis would be possible.  

Happy to take a shot at adding it and making a PR but thought I would create the issue first to see what you thought.

**Comment by jts** [comment]
Yeah, I think this is a good thing to support. I'd leave it off by default because I want to use the output to spot potential sequencing problems but this would be a good option for the config.

**Comment by jts** [comment]
I looked into this and noticed that nextstrain masks the multiple alignment using a custom script that isn't shipped in `augur`: https://github.com/nextstrain/ncov/blob/master/rules/builds.smk#L114

`augur mask` can mask the consensus sequences but requires the masking sites as BED, which makes integration a bit more complicated.

**Comment by jts** [comment]
Cleaning up old unresolved issues
