### ISSUE TITLE
all_summary_qc fails if data_root not set to 'data'

### ISSUE THREAD

**Issue by DarianHole** [jts/ncov-tools#22]
Running the same dataset with different config `data_root` settings causes a failure in the `snakemake -s qc/Snakefile all_qc_summary --cores 1` command where the analysis fails due to missing input files. Here is the error for when I set the data_root to 'run':

```
Building DAG of jobs...
MissingInputException in line 361 of /home/CSCScience.ca/dhole/ncov-tools/ncov-tools/qc/Snakefile:
Missing input files for rule make_sample_qc_summary:
data/BR3091.pass.vcf.gz
data/BR3091.consensus.fasta
```

If I set the `data_root` to 'data'  to match the error, I get an expected outcome and the correct tsv files. I have not tested this with other data_root names but I assume that they may run into the same issue

**Comment by rdeborja** [comment]
Thanks @DarianHole, just submitted a PR to fix this:
https://github.com/jts/ncov-tools/pull/23

**Comment by rdeborja** [comment]
Merged, let me know if there's any other issues.

**Comment by DarianHole** [comment]
Ya no problem! I didn't think it would be a hard fix. I'll do a quick test on it now!
