### ISSUE TITLE
get_qc.py getting passed unrecognized argument --run_name

### ISSUE THREAD

**Issue by DarianHole** [jts/ncov-tools#26]
Hi again,

I've encountered a new issue with running the `all_qc_summary` command. In this, the `get_qc.py` script is failing as it is being passed the run name as the argument `--run name <name>` when that is not an argument that it has available to it.

```
Error in rule make_sample_qc_summary:
    jobid: 9
    output: qc_analysis/RV3258-20.summary.qc.tsv
    shell:
        ...

usage: get_qc.py [-h] [-c CONSENSUS] [-v VARIANTS] [-e COVERAGE] [-i]
                 [-m META] [-a ALLELES] [-s SAMPLE] [-p PLATFORM]
get_qc.py: error: unrecognized arguments: --run_name darian
```

**Comment by rdeborja** [comment]
After activating the conda environment, what version do you get when you type `pip show ncov_parser`?  The latest version is 0.5.1 which contains the latest changes.  After downloading, I've had to re-install the parser package times twice for some odd reason.

**Comment by DarianHole** [comment]
Oh that is the issue, I completely forgot I had to do that again

Thanks
