### ISSUE TITLE
Generation of summary reports without inputting negative control names

### ISSUE THREAD

**Issue by DarianHole** [jts/ncov-tools#31]
I was curious if it was possible to generate the reports made by the command `snakemake -s qc/Snakefile all_qc_reports --cores ##` without specifying any negative control sample names in the config file (optional parameter). Hopefully I didn't miss something silly on this...

I haven't been able to get it to work under these circumstances with it failing in the generation of the negative sample report when no names are given (makes sense). Thus, I was wondering if there was a way to skip this step when no negative sample names are given in the config?

Otherwise it works as expected on my data. I just would like this for some of the older samples that I need to re-test which do not have any negative controls associated and I don't want to put one in randomly as a placeholder if I can avoid it. I will go that route if necessary though.

Thanks,
Darian

**Comment by jts** [comment]
Good spot, this should be possible. I'll modify the negative control script to accept no files as valid input so the file is created, but empty.

Jared

**Comment by DarianHole** [comment]
Awesome, thanks Jared!

**Comment by jts** [comment]
It turns out that snakemake doesn't like the `input:` field to be empty, so I had to disable the report instead of making it empty
