### ISSUE TITLE
Negative control samples and filenames

### ISSUE THREAD

**Issue by rdeborja** [jts/ncov-tools#34]
As discussed during the CanCOGen meeting on August 24, an issue arose where negative control samples identified in the config.yaml were not properly handled if the associated files were not found.

**Comment by DarianHole** [comment]
Yes thank you very much for looking into this!

For our pipeline, sometimes the negative control gets filtered out (when it contains no reads) so I was hoping if that happens that snakemake won't fail and instead just skips the negative control step if that makes sense. I can clarify more if needed

Darian

**Comment by jts** [comment]
In that case, is the BAM present but empty or is the BAM missing entirely?

**Comment by DarianHole** [comment]
No BAM file generated.

I am also attempting to address this on my end by removing the negative control check line in the config automatically when this happens but I was wondering if its possible to also add it to ncov-tools to skip the one check (as it seems to be the only issue)

**Comment by jts** [comment]
Ok, I think we can handle it but I'll probably put it behind a flag (`skip_empty_negatives: true`) so that the more typical case (the user didn't enter the control names correctly) ends in an error

**Comment by DarianHole** [comment]
That sounds perfect! Thanks again Jared and Richard!

**Comment by danieljbridges** [comment]
Great to see this has already been reported some time ago. We regularly have negatives with no corresponding bam file, but the flag `skip_empty_negatives: true` doesn't seem to work. Has this been implemented yet?

**Comment by jts** [comment]
Hi @danieljbridges,

Sorry but this slipped so hasn't been implemented yet. Thanks for bumping this issue, we'll try to add it.

Jared

**Comment by danieljbridges** [comment]
Thanks @jts - looking forward to seeing this added!

**Comment by rdeborja** [comment]
@danieljbridges @DarianHole I just merged a PR that checks the negative controls in the config yaml file, if the negative controls samples don't have a valid BAM file it skips them preventing `ncov-tools` from failing during report creation.

**Comment by DarianHole** [comment]
Awesome, thanks @rdeborja! 

I'll have to see if I can test this out today or tomorrow!

**Comment by danieljbridges** [comment]
Now that I have sorted out my environment I have been able to test this and it works perfectly. Thanks so much for this very useful addition!
