### ISSUE TITLE
Make the completeness threshold for including a sample in the tree-snp plot configurable

### ISSUE THREAD

**Issue by jts** [jts/ncov-tools#44]
Currently the threshold is 75%, @nknox suggested we allow this to be set in config.yaml

**Comment by rdeborja** [comment]
@nknox I have configured the workflow to accept a `completeness_threshold` in the `config.yaml` file to allow custom thresholds to be used for the inclusion of samples to the SNP tree.  This has since been tested, submitted as a PR, reviewed and merged into master and is available for use.
