### ISSUE TITLE
One target to rule them all?

### ISSUE THREAD

**Issue by andersgs** [jts/ncov-tools#48]
Should there be an option of `snakemake -s <path>/Snakefile` that just runs all the targets, rather than having one run the three individual targets separately?

Or, could one conceivably submit the targets to separate jobs on an HPC cluster and run all three in parallel? I haven't tried, and haven't read enough of the code yet to understand if that is possible.

Cheers. Anders.

**Comment by andersgs** [comment]
And, if not possible to run them in parallel, do they need to be run in that order (i.e., as specified in the docs?)?

**Comment by jts** [comment]
Hi Anders,

This is something I definitely want to clean up as I agree its a bit confusing now as we've added many targets over time. Right now when I build everything I run `snakemake -s <path>/Snakefile all_qc_sequencing all_qc_analysis all_qc_reports` but the order does not matter. 

I'll make it run all three of those targets by default.

Jared

**Comment by jts** [comment]
By default it should run all the QC targets now
