### ISSUE TITLE
Singularity containerisation to enable use in conda-limited environments

### ISSUE THREAD

**Issue by fmaguire** [jts/ncov-tools#49]
HPC/Compute Canada doesn't support conda so running the workflow is non-trivial.

They can use singularity so the options would be:

1. Create a container that has all the dependencies installed and have host install of snakemake executing rules in that environment (easier but less portable)
2. Create a container encompassing the entire tool (more portable but more complex).

Once done, this build can be triggered on a new release in github actions e.g. https://github.com/jaleezyy/covid-19-signal/blob/master/.github/workflows/dockerpublish.yml

2. is probably the better choice using the conda docker container as a base image  e.g. singularity build of https://github.com/jaleezyy/covid-19-signal/blob/master/resources/Dockerfile_pipeline  installing mamba on this and then just scripting the README install instructions SHOULD work although the nested pangolin workflow might be a slight tripping point

**Comment by poquirion** [comment]
Hello, I am with the C3G and Compute Canada.  

A reasonable solution would be to have two containers, one with the dependencies, with fixed versions of the tools minus snakemake, and one with the ncov-tools scripts that depend on the previous container. Having a version number for all the tools in the environment file could also speed up the build speed and help reproducibility (https://www.anaconda.com/blog/understanding-and-improving-condas-performance)

The goal for us will be to run the pipeline using  `snakemake --use-singularity --use-conda` paradigm, where snakemake in installed on the host (not in a container).

I can fork the repo and propose something.

**Comment by jts** [comment]
Thanks @poquirion, I'd be happy to take a look if you want to fork and propose some changes. You may wish to have a look at issue #47 as we're discussing some other changes to the workflow that may effect the environments.

**Comment by jts** [comment]
@poquirion just a head's up that I merged the first stage of the refactor - I suggest you update your fork before starting on the singularity changes

**Comment by jts** [comment]
Resolved by @poquirion
