### ISSUE TITLE
Parser from master branch in github installed in dependecies installed 

### ISSUE THREAD

**Issue by poquirion** [jts/ncov-tools#51]
The last line of 
`workflow/envs/environment.yml` is 

`git+https://github.com/jts/ncov-tools.git#egg=ncov_parser&subdirectory=parser`

it installs the parser from the github's master branch. I think it should not be there, especially if you do not want the master branch version of the parser... Also, if you follow the README it seems redundant.

**Comment by jts** [comment]
We are currently making `ncov-parser` into a standalone package on pip, it will soon be moved to the environment.yaml

**Comment by poquirion** [comment]
In the mean time I might simply pull it out of environment.yml at least for the container version I am working on.
