### ISSUE TITLE
Conda package name for parasail is 'parasail-python'

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-tools#57]
The conda package name for `parasail` is `parasail-python`:

https://anaconda.org/bioconda/parasail-python

But it's listed as `parasail` in the environment file:

https://github.com/jts/ncov-tools/blob/511f5efbdb9f3f13b37529cfe287408f30b0a0a7/workflow/envs/environment.yml#L19

**Comment by jts** [comment]
Thanks Dan, good catch. I’ll fix that soon.

**Comment by jts** [comment]
Oh, just saw the PR - thanks for that too.
