### ISSUE TITLE
Documentation for ncov-watch input

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-tools#59]
The rule for preparing the `ncov-watch` input refers to two new `config.yaml` entries (`mutation_set` and `spike_mutations`):

https://github.com/jts/ncov-tools/blob/4280173d779b68c2ff3d037835fc7db491fb07d4/workflow/rules/defaults.smk#L54-L55

...but there is no documentation in the README.md describing the formats of those inputs.

Could a description of how to configure the `ncov-watch` inputs be added to the README?

**Comment by jts** [comment]
Will do, thanks for pointing that out.

**Comment by jts** [comment]
Made a first pass at it in this section:

https://github.com/jts/ncov-tools#other-optional-configuration

Let me know how it looks.

**Comment by dfornika** [comment]
I see. That is helpful, thanks. I misunderstood and thought that there were two separate config.yaml entries (`mutation_set` and `spike_mutations`). But it's a single entry `mutation_set` with default value `spike_mutations`.
