### ISSUE TITLE
Latest pangolin release breaks ncov-tools

### ISSUE THREAD

**Issue by will-rowe** [jts/ncov-tools#64]
Hiya,

The latest release of pangolin seems to have dropped thread support: https://github.com/cov-lineages/pangolin/issues/136

Pangolin now complains at the `-t` so I  had to downgrade the pangolin version in the ncov-tools env to 2.1.11

Not sure if you want to fix pangolin version or adjust the command to drop threads - happy to PR if you want either.

Cheers,

Will

**Comment by jts** [comment]
Thanks for letting me know Will, I'll look at this

**Comment by aineniamh** [comment]
I can reinstate it- but it hasn't been a functional flag in latest releases. It seems that dropping it may be causing more issues than solving, so I can update so using -t won't break anything.

**Comment by jts** [comment]
Ah, my commit crossed with your comment @aineniamh! I've removed the flag, if it isn't functional I'll keep it this way in ncov-tools but understand if you want to put it back in for compatibility with other workflows/pipelines.

**Comment by aineniamh** [comment]
Ah no problem! Sorry about that again, I had been doing a code 'spring-clean' and dropped quite a lot of the legacy code (including the now non-functional thread flag). 
I've added a catch in that prints a warning but doesn't break in the latest release (https://github.com/cov-lineages/pangolin/releases/tag/v2.2.2), and hopefully we can support multithreading again in the future.
