### ISSUE TITLE
pangolin no longer has '-lv' flag

### ISSUE THREAD

**Issue by dfornika** [jts/ncov-tools#65]
This commit:

https://github.com/cov-lineages/pangolin/commit/d1ec05441be70c135e43e3be1b5b310154de8b3b#diff-60adb0b1d86889ec80ab00b2fe0ad9d0bedf1d3d250b52e8f56a63fba8533231

...removed the `-lv` flag that is used here:

https://github.com/jts/ncov-tools/blob/bf5aa2d878960fa436fd1ce82e72ee98dbc93223/workflow/rules/analysis.smk#L90

...which leads to pipeline failure.

**Comment by jts** [comment]
Thanks @dfornika for reporting and @rdeborja for the fix.
