### ISSUE TITLE
PDF reports fails to generate due to missing "lineage_notes" key

### ISSUE THREAD

**Issue by DarianHole** [jts/ncov-tools#69]
Hi everyone,

After the [latest update](https://github.com/jts/ncov-tools/commit/29db4e54be3fa38133c0fd307c0426ec8fa9b81a) to the pdf report I keep getting a key error for missing the `lineage_notes` key. For the moment I've gotten it to work by checking out to the commit before this change (01e044b3e56ef2460abf93cf7d475072df23f078).

Error:
```
rule make_report_tex:
    input: qc_reports/nml_summary_qc.tsv, lineages/nml_pangolin_version.txt, plots/nml_tree_snps.pdf
    output: qc_reports/nml.tex
    jobid: 2
    wildcards: prefix=nml

 

Traceback (most recent call last):
  File "/ncov-tools/workflow/rules/../scripts/generate_report.py", line 355, in <module>
    write_summary_qc_section()
  File "/ncov-tools/workflow/rules/../scripts/generate_report.py", line 274, in write_summary_qc_section
    tsv_to_table(args.summary_qc_table.format(run_name=args.run_name), tf)
  File "/ncov-tools/workflow/rules/../scripts/generate_report.py", line 95, in tsv_to_table
    del row[k]
KeyError: 'lineage_notes'
```

Let me know if I've missed anything to easily solve this!

Thanks,
Darian

**Comment by jts** [comment]
This change requires updating the ncov-parser library in the environment to version 0.6.4

**Comment by DarianHole** [comment]
Ah thanks, I keeping missing those updates
