### ISSUE TITLE
homoplastic sites

### ISSUE THREAD

**Issue by agmcarthur** [jts/ncov-tools#9]
It would be interesting if the tree could label which positions are suspected of homoplasy: https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473

**Comment by jts** [comment]
Cleaning up old issues, I think this is now out-of-scope

**Comment by raphenya** [comment]
@nodrogluap highlighted this might be worth re-opening see 
- Repository: https://github.com/nodrogluap/pokay/tree/master/data and 
- VCFs: https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/master/subset_vcf/problematic_sites_sarsCov2.mask.vcf
