### ISSUE TITLE
pangolin error

### ISSUE THREAD

**Issue by danieljbridges** [jts/ncov-tools#90]
Hi there,

I just did a fresh install of the `ncov-tools` environment and there appears to be an issue with pangolin. I was running a  all_final_report and got the following error [2021-06-25T192934.968980.snakemake.log](https://github.com/jts/ncov-tools/files/6717991/2021-06-25T192934.968980.snakemake.log):

TypeError: can't pickle _thread.RLock objects
[Fri Jun 25 19:28:28 2021]
Error in rule make_lineage_assignments:
    jobid: 10
    output: lineages/C30_lineage_report.csv
    shell:
        pangolin --outfile lineages/C30_lineage_report.csv qc_analysis/C30_consensus.fasta                                           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!) 

I ran the pangolin command in isolation in the same environment and got the same error. I then switched to another conda env with pangolin and was able to successfully generate a lineage-report from the same fasta. Any thoughts on what the issue is?

**Comment by rdeborja** [comment]
Hi Daniel,

I re-created my conda environment and ran `ncov-tools` with the latest versions of packages and ran it on both Illumina and ONT datasets but am unable to reproduce this issue.  Is the version of `pangolin`, `scorpio`, and `pangoLEARN` different between the two conda environments you were using?  I currently have:
```
pangolin 3.1.5
pangoLEARN 2021-06-15
scorpio 0.3.4
```

Cheers,
Richard

**Comment by danieljbridges** [comment]
Hi @rdeborja,

Thanks for looking into this. I stupidly deleted my working `ncov-qc` environment. Have recreated it multiple times, but keep getting the same error. When I compare 'pangolin' / 'scorpio' between my 'pangolin' env (works perfectly) and my 'ncov-tools' env, they are identical to yours. 

I looked closer during the environment creation and saw these errors:

```
SafetyError: The package for snpeff located at /home/dan/miniconda3/pkgs/snpeff-5.0-hdfd78af_1
appears to be corrupted. The path 'share/snpeff-5.0-1/snpEff.config'
has an incorrect size.
  reported size: 10773532 bytes
  actual size: 10773563 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::tbb-2020.3-hfd86e86_0, bioconda/linux-64::usher-0.3.2-h7b4d82f_0
  path: 'lib/libtbbmalloc.so.2'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::tbb-2020.3-hfd86e86_0, bioconda/linux-64::usher-0.3.2-h7b4d82f_0
  path: 'lib/libtbbmalloc_proxy.so.2'

I then did 'conda clean -a' and recreated the environment without any errors. Am really confused about this. Any other ideas on how to troubleshoot it?

**Comment by danieljbridges** [comment]
Ok this is clearly a install-specific issue as everything worked perfectly on another computer. After removing and reinstalling the env > 10 times, am unsure what else to do. Apologies - understand this isn't your problem, but if anyone has any suggestions or pointers, I am all ears!

**Comment by rdeborja** [comment]
Thanks for letting me know @danieljbridges.  I was frantically re-installing `ncov-tools` and `pangolin` separately on various platforms but have not been able to reproduce the issue.  I did encounter the same `SafetyError` and `ClobberError` but attributed it to a package caching error not associated with the issue running `pangolin`.

**Comment by kdmack87** [comment]
Hi Daniel - I had a similar error coming up in ncov-tools regarding snpEff. As with your case, it happened after I re-created our ncov-tools environment. Based on the error message, it was tracing back to an install of snpEff within a separate conda environment that we use (mamba-signal - https://github.com/jaleezyy/covid-19-signal). Recreating this mamba-signal environment as well cleared the snpEff safety error. Is your version of snpEff in a specific environment, or in your base environment? It might be a matter of either uninstalling or updating a conflicting version of snpEff that's located somewhere else on your system?

**Comment by danieljbridges** [comment]
Thanks all for your help and suggestions. I found out there were some pangolin packages in the `base` folder that appeared to be interfere with the `ncov-qc` environment... Everything is working well now....
